services:
  mysql:
    image: mysql:8.4.11
    container_name: game_realtime_mysql
    command: ["--default-time-zone=+08:00"]
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: game_realtime
      MYSQL_USER: game
      MYSQL_PASSWORD: game123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: game_realtime_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
